import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.2/+esm';
import { buildStudentRows, isUnauthorizedError, parseAssessmentScore } from './app-core.mjs';

const SUPABASE_URL = 'https://tyhwkudogenugnnfgxav.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_UvoJmNRNQXBuQVO1w7qCAA_Aqy47QYo';
const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
const navs=document.querySelectorAll('.nav'),pages=document.querySelectorAll('.page');
const studentsPage=document.getElementById('students'),authPanel=document.getElementById('authPanel'),studentContent=document.getElementById('studentContent'),studentBody=document.getElementById('studentBody'),studentSearch=document.getElementById('studentSearch'),attendanceDetail=document.getElementById('attendanceDetail'),attendanceGrid=document.getElementById('attendanceGrid'),authMessage=document.getElementById('authMessage'),sessionLabel=document.getElementById('sessionLabel'),signOutButton=document.getElementById('signOutButton');
let session=null,studentRows=[],statusMeanings=new Map();
navs.forEach(button=>{button.onclick=()=>{navs.forEach(item=>item.classList.remove('active'));pages.forEach(item=>item.classList.remove('active'));button.classList.add('active');document.getElementById(button.dataset.page).classList.add('active');if(button.dataset.page==='students')refreshStudentsView();};});
document.getElementById('attendanceJump').onclick=()=>document.querySelector('[data-page="students"]').click();
function setState(name,message=''){studentsPage.dataset.state=name;document.querySelectorAll('[data-student-state]').forEach(el=>{el.hidden=el.dataset.studentState!==name;});const target=document.querySelector(`[data-student-state="${name}"]`);if(target&&message)target.textContent=message;}
async function fetchAll(table,columns,orderColumn){const pageSize=1000,rows=[];for(let from=0;;from+=pageSize){let query=supabase.from(table).select(columns).range(from,from+pageSize-1);if(orderColumn)query=query.order(orderColumn,{ascending:true});const{data,error}=await query;if(error)throw error;rows.push(...(data??[]));if(!data||data.length<pageSize)break;}return rows;}
async function loadStudents(){setState('loading');try{const[students,enrollments,grades,academicYears,attendanceMonths,statusCodes]=await Promise.all([fetchAll('students','student_id,student_name,gender,date_of_birth,social_category,program_type','student_name'),fetchAll('student_grade_enrollments','student_grade_enrollment_id,student_id,academic_year_id,grade_id,source_grade_label','student_grade_enrollment_id'),fetchAll('grades','grade_id,grade_code,grade_name,sort_order','sort_order'),fetchAll('academic_years','academic_year_id,year_label','year_label'),fetchAll('attendance_months','attendance_month_id,student_id,academic_year_id,grade_id,month_number,source_month_label,reported_days_present,reported_days_absent,reported_attendance_percentage','attendance_month_id'),fetchAll('attendance_status_codes','status_code,meaning','status_code')]);statusMeanings=new Map(statusCodes.map(row=>[row.status_code,row.meaning]));studentRows=buildStudentRows({students,enrollments,academicYears,grades,attendanceMonths});renderStudentRows(studentRows);setState(studentRows.length?'ready':'empty');}catch(error){if(isUnauthorizedError(error)){await supabase.auth.signOut({scope:'local'});session=null;updateAuthUi('Your session expired. Sign in again to view student data.');setState('auth');return;}console.error(error);setState('error',`Could not load student data: ${error.message||'Unknown error'}`);}}
function renderStudentRows(rows){studentBody.innerHTML='';for(const row of rows){const tr=document.createElement('tr');const pct=row.attendancePercent==null?'—':`${Number(row.attendancePercent).toFixed(1)}%`;tr.innerHTML=`<td><button class="linkbutton" data-student-id="${escapeHtml(row.student_id)}">${escapeHtml(row.student_name)}</button><small>${escapeHtml(row.student_id)}</small></td><td>${escapeHtml(row.grade)}</td><td>${escapeHtml(row.academicYear)}</td><td>${escapeHtml(row.attendanceMonthLabel)}</td><td>${pct}</td>`;tr.querySelector('button').onclick=()=>loadAttendanceDetail(row);studentBody.appendChild(tr);}}
async function loadAttendanceDetail(student){attendanceDetail.hidden=false;document.getElementById('attendanceTitle').textContent=`${student.student_name} • ${student.attendanceMonthLabel}`;attendanceGrid.innerHTML='<div class="muted">Loading attendance days…</div>';if(!student.attendanceMonthId){attendanceGrid.innerHTML='<div class="muted">No attendance month is available for this student.</div>';return;}const{data,error}=await supabase.from('attendance_days').select('attendance_day_id,day_of_month,raw_status_code,normalized_status_code').eq('attendance_month_id',student.attendanceMonthId).order('day_of_month',{ascending:true});if(error){if(isUnauthorizedError(error)){await supabase.auth.signOut({scope:'local'});session=null;updateAuthUi('Your session expired. Sign in again to view student data.');setState('auth');return;}attendanceGrid.innerHTML=`<div class="errorText">Could not load attendance detail: ${escapeHtml(error.message)}</div>`;return;}if(!data?.length){attendanceGrid.innerHTML='<div class="muted">No daily attendance records are available for this month.</div>';return;}attendanceGrid.innerHTML=data.map(day=>{const code=day.normalized_status_code||day.raw_status_code;const meaning=statusMeanings.get(code)||(code==='N'?'Unresolved':'Unknown');return `<div class="daychip"><b>${day.day_of_month}</b><span>${escapeHtml(code)}</span><small>${escapeHtml(meaning??'')}</small></div>`;}).join('');}
function filterStudents(){const query=studentSearch.value.trim().toLowerCase();const filtered=studentRows.filter(row=>`${row.student_name} ${row.student_id} ${row.grade}`.toLowerCase().includes(query));renderStudentRows(filtered);if(!filtered.length&&studentRows.length)setState('empty');else if(studentRows.length)setState('ready');}
studentSearch.addEventListener('input',filterStudents);
document.getElementById('signInForm').addEventListener('submit',async event=>{event.preventDefault();authMessage.textContent='Signing in…';const form=new FormData(event.currentTarget);const{error}=await supabase.auth.signInWithPassword({email:String(form.get('email')),password:String(form.get('password'))});if(error)authMessage.textContent=error.message;});
signOutButton.onclick=async()=>{await supabase.auth.signOut();};
function updateAuthUi(message=''){authPanel.hidden=Boolean(session);studentContent.hidden=!session;signOutButton.hidden=!session;sessionLabel.textContent=session?.user?.email?`Signed in as ${session.user.email}`:'Not signed in';if(message)authMessage.textContent=message;}
async function refreshStudentsView(){if(!session){updateAuthUi();setState('auth');return;}updateAuthUi();await loadStudents();}
const{data:{session:initialSession}}=await supabase.auth.getSession();session=initialSession;updateAuthUi();if(document.querySelector('[data-page="students"]').classList.contains('active'))refreshStudentsView();
supabase.auth.onAuthStateChange((_event,nextSession)=>{session=nextSession;updateAuthUi();if(document.querySelector('[data-page="students"]').classList.contains('active'))queueMicrotask(()=>refreshStudentsView());});
document.querySelectorAll('[data-score-input]').forEach(input=>{input.addEventListener('change',()=>{const parsed=parseAssessmentScore(input.value);input.setCustomValidity(parsed?'':'Enter 0–10 or A for Absent.');if(parsed)input.value=parsed.raw;input.reportValidity();});});
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}